"""Initial tables for vehicle make, model, trim

Revision ID: b158bad8f9ee
Revises: 8281b979a03d
Create Date: 2020-03-27 05:52:09.158381

"""
from alembic import op
import sqlalchemy as sa
import tksqla.migration_types


# revision identifiers, used by Alembic.
revision = 'b158bad8f9ee'
down_revision = '8281b979a03d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tksqla_vehiclemake',
    sa.Column('id', tksqla.migration_types.Integer(), nullable=False),
    sa.Column('name', tksqla.migration_types.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tksqla_vehiclemodel',
    sa.Column('id', tksqla.migration_types.Integer(), nullable=False),
    sa.Column('name', tksqla.migration_types.String(), nullable=False),
    sa.Column('vehiclemake_id', tksqla.migration_types.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vehiclemake_id'], ['tksqla_vehiclemake.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'vehiclemake_id')
    )
    op.create_table('tksqla_vehicletrim',
    sa.Column('id', tksqla.migration_types.Integer(), nullable=False),
    sa.Column('name', tksqla.migration_types.String(), nullable=False),
    sa.Column('vehiclemodel_id', tksqla.migration_types.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vehiclemodel_id'], ['tksqla_vehiclemodel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'vehiclemodel_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tksqla_vehicletrim')
    op.drop_table('tksqla_vehiclemodel')
    op.drop_table('tksqla_vehiclemake')
    # ### end Alembic commands ###
